fix

diff --git a/.github/workflows/staging-deploy.yml b/.github/workflows/staging-deploy.yml
--- a/.github/workflows/staging-deploy.yml
+++ b/.github/workflows/staging-deploy.yml
@@ -2,8 +2,8 @@ name: Staging Deploy
 
 on:
   push:
-    branches:
-      - develop
+    # branches:
+    #   - develop
 
 jobs:
   docker-build:
@@ -25,36 +25,68 @@ jobs:
           docker build -t $IMAGE_NAME . -f docker/prod/ci.Dockerfile
           docker push $IMAGE_NAME
 
-  deploy:
-    runs-on: self-hosted
+  setup-uptime:
+    runs-on: ubuntu-latest
     needs: docker-build
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
+      - name: Checkout Code
+        uses: actions/checkout@v3
 
-    - name: Docker Login to GitHub Container Registry
-      run: |
-        echo "${{ secrets.GH_UPTIME_PAT }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
+      - name: Update AWS Security Groups & Setup SSH Key
+        uses: ./.github/actions/setup
+        with:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          REGIONS: "${{ secrets.UPTIME_STAGING_AWS_REGION }}"
+          SECURITY_GROUPS: "${{ secrets.UPTIME_STAGING_SECURITY_GROUP }}"
 
-    - name: Clean and Run Docker container
-      run: |
-        COMMIT_HASH=$(git rev-parse --short HEAD)
-        docker stop uptime-backend || true
-        docker rm uptime-backend || true
-        COMMIT_HASH=$(git rev-parse --short HEAD)
-        docker run -d \
-          --name uptime-backend \
-          -p 5000:5000 \
-          -e DB_CONNECTION_STRING=mongodb://172.31.40.27:27017/uptime_db \
-          -e REDIS_URL=redis://172.31.40.27 \
-          ghcr.io/${{ github.repository_owner }}/uptime:${COMMIT_HASH}
+      - name: Setup SSH Key for GitHub
+        env:
+          SSH_KEY: ${{ secrets.UPTIME_STAGING_SSH_KEY }}
+        shell: bash
+        run: |
+          mkdir -p ~/.ssh || true
+          echo "${SSH_KEY}" > ~/.ssh/id_rsa_uptime
+          chmod 600 ~/.ssh/id_rsa_uptime
+          ssh-keygen -l -f ~/.ssh/id_rsa_uptime
 
-  cleanup:
-    runs-on: self-hosted
-    if: always()
-    needs: deploy
-    steps:
-    - name: 'Cleanup build folder'
-      run: |
-        rm -rf ./${{github.workspace}}\*
+      - name: Install Required Packages on Remote Server
+        uses: ./.github/actions/install
+        with:
+          REMOTE_USER: "ubuntu"
+          SERVER_IP: "${{ secrets.UPTIME_STAGING_HOST_IP }}"
+          
+  # deploy:
+  #   runs-on: self-hosted
+  #   needs: docker-build
+
+  #   steps:
+  #   - name: Checkout code
+  #     uses: actions/checkout@v2
+
+  #   - name: Docker Login to GitHub Container Registry
+  #     run: |
+  #       echo "${{ secrets.GH_UPTIME_PAT }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
+
+  #   - name: Clean and Run Docker container
+  #     run: |
+  #       COMMIT_HASH=$(git rev-parse --short HEAD)
+  #       docker stop uptime-backend || true
+  #       docker rm uptime-backend || true
+  #       COMMIT_HASH=$(git rev-parse --short HEAD)
+  #       docker run -d \
+  #         --name uptime-backend \
+  #         -p 5000:5000 \
+  #         -e DB_CONNECTION_STRING=mongodb://172.31.40.27:27017/uptime_db \
+  #         -e REDIS_URL=redis://172.31.40.27 \
+  #         ghcr.io/${{ github.repository_owner }}/uptime:${COMMIT_HASH}
+
+  # cleanup:
+  #   runs-on: self-hosted
+  #   if: always()
+  #   needs: deploy
+  #   steps:
+  #   - name: 'Cleanup build folder'
+  #     run: |
+  #       rm -rf ./${{github.workspace}}\*
